/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import Entidades.EntidadMedidas;
import Entidades.EntidadPedido;
import clases.Conexion;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jsant
 */
public class Pedidos extends javax.swing.JFrame {
    private EntidadPedido pedido;
    private Conexion conexion;
    //private Conexion conexion = new Conexion();
    /**
     * Creates new form Pedidos
     */
    public Pedidos() throws SQLException {
        conexion = new Conexion();
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabelBusto = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jLabelCintura = new javax.swing.JLabel();
        jLabelTalle = new javax.swing.JLabel();
        jLabelLargoFalda = new javax.swing.JLabel();
        jLabelEspalda = new javax.swing.JLabel();
        jLabelCadera = new javax.swing.JLabel();
        jLabelBocaManga = new javax.swing.JLabel();
        jLabelLargoManga = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtEspalda = new javax.swing.JTextField();
        txtBocaM = new javax.swing.JTextField();
        txtLargoM = new javax.swing.JTextField();
        txtCadera = new javax.swing.JTextField();
        txtLargoF = new javax.swing.JTextField();
        txtTalle = new javax.swing.JTextField();
        txtCintura = new javax.swing.JTextField();
        txtBusto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtFechaI = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtFechaE = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtTallado1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtTallado2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnHistorial = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAccesorios = new javax.swing.JTextArea();
        jLabelFondoVerde = new javax.swing.JLabel();
        jLabelFondoVerde2 = new javax.swing.JLabel();
        jLabelFondoVerde1 = new javax.swing.JLabel();
        jLabelFondoVerde4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setText("Registro Pedido");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 370, -1));

        jLabelBusto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelBusto.setText("Busto: ");
        getContentPane().add(jLabelBusto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane2.setViewportView(txtDescripcion);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 570, 90));

        jLabelCintura.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelCintura.setText("Cintura: ");
        getContentPane().add(jLabelCintura, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        jLabelTalle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelTalle.setText("Talle: ");
        getContentPane().add(jLabelTalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));

        jLabelLargoFalda.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelLargoFalda.setText("Largo Falda: ");
        getContentPane().add(jLabelLargoFalda, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, -1));

        jLabelEspalda.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelEspalda.setText("Espalda: ");
        getContentPane().add(jLabelEspalda, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, -1, -1));

        jLabelCadera.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelCadera.setText("Cadera: ");
        getContentPane().add(jLabelCadera, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, -1, -1));

        jLabelBocaManga.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelBocaManga.setText("Boca Manga: ");
        getContentPane().add(jLabelBocaManga, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, -1, -1));

        jLabelLargoManga.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelLargoManga.setText("Largo Manga: ");
        getContentPane().add(jLabelLargoManga, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Descripción: ");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));
        getContentPane().add(txtEspalda, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 290, 140, -1));
        getContentPane().add(txtBocaM, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, 140, -1));
        getContentPane().add(txtLargoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, 140, -1));
        getContentPane().add(txtCadera, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 240, 140, -1));
        getContentPane().add(txtLargoF, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 140, -1));
        getContentPane().add(txtTalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 140, -1));

        txtCintura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCinturaActionPerformed(evt);
            }
        });
        getContentPane().add(txtCintura, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 140, -1));

        txtBusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBustoActionPerformed(evt);
            }
        });
        getContentPane().add(txtBusto, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 140, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Confirmar");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 330, -1, -1));

        btnGuardar.setBackground(new java.awt.Color(0, 0, 255));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 750, -1, -1));

        btnCancelar.setBackground(new java.awt.Color(255, 0, 0));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 750, 90, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Fecha Inicial");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, -1, -1));

        txtFechaI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaIActionPerformed(evt);
            }
        });
        getContentPane().add(txtFechaI, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, 140, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("Fecha Entrega");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 560, -1, -1));

        txtFechaE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaEActionPerformed(evt);
            }
        });
        getContentPane().add(txtFechaE, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 560, 140, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("Tallado 1");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 610, -1, -1));
        getContentPane().add(txtTallado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 610, 140, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setText("Tallado 2");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 660, -1, -1));
        getContentPane().add(txtTallado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 660, 140, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setText("Accesorios");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 510, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setText("Cliente");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 610, -1, -1));
        getContentPane().add(txtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 610, 140, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setText("Total");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 660, -1, -1));
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 660, 140, -1));

        btnHistorial.setBackground(new java.awt.Color(0, 0, 0));
        btnHistorial.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHistorial.setForeground(new java.awt.Color(255, 255, 255));
        btnHistorial.setText("Historial");
        btnHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialActionPerformed(evt);
            }
        });
        getContentPane().add(btnHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 750, 90, -1));

        txtAccesorios.setColumns(20);
        txtAccesorios.setRows(5);
        jScrollPane1.setViewportView(txtAccesorios);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 500, -1, -1));

        jLabelFondoVerde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoVerde.jpg"))); // NOI18N
        getContentPane().add(jLabelFondoVerde, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 410, 320, 410));

        jLabelFondoVerde2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoVerde.jpg"))); // NOI18N
        jLabelFondoVerde2.setText("jLabel1");
        getContentPane().add(jLabelFondoVerde2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 320, -1));

        jLabelFondoVerde1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoVerde.jpg"))); // NOI18N
        getContentPane().add(jLabelFondoVerde1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 410));

        jLabelFondoVerde4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoVerde.jpg"))); // NOI18N
        getContentPane().add(jLabelFondoVerde4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 610, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCinturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCinturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCinturaActionPerformed

    private void txtBustoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBustoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBustoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        pedido = new EntidadPedido();
        pedido.setDescripcion(txtDescripcion.getText());
        pedido.setFechaEntrega(txtFechaE.getText());
        pedido.setFechaInicial(txtFechaI.getText());
        pedido.setCliente(txtCliente.getText());
        pedido.setTotal(Integer.parseInt(txtTotal.getText()));
        pedido.setAccesorios(txtAccesorios.getText());
        pedido.setFechaTallado(txtTallado1.getText());
        pedido.setFechaTallado2(txtTallado2.getText());
        pedido.getMedidas().setBusto(Float.parseFloat(txtBusto.getText()));
        pedido.getMedidas().setCintura(Float.parseFloat(txtCintura.getText()));
        pedido.getMedidas().setTalle(Float.parseFloat(txtTalle.getText()));
        pedido.getMedidas().setLargoFalda(Float.parseFloat(txtLargoF.getText()));
        pedido.getMedidas().setCadera(Float.parseFloat(txtCadera.getText()));
        pedido.getMedidas().setEspalda(Float.parseFloat(txtEspalda.getText()));
        pedido.getMedidas().setLargoManga(Float.parseFloat(txtLargoM.getText()));
        pedido.getMedidas().setBocaManga(Float.parseFloat(txtBocaM.getText()));
        pedido.Create(conexion);
        JOptionPane.showMessageDialog(null, "Los datos se guardaron correctamente");
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Menu newframe = new Menu();
        newframe.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtFechaIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaIActionPerformed

    private void txtFechaEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaEActionPerformed

    private void btnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialActionPerformed
        PedidosVer newframe = new PedidosVer();
        newframe.setVisible(true);
    }//GEN-LAST:event_btnHistorialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Pedidos().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnHistorial;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabelBocaManga;
    private javax.swing.JLabel jLabelBusto;
    private javax.swing.JLabel jLabelCadera;
    private javax.swing.JLabel jLabelCintura;
    private javax.swing.JLabel jLabelEspalda;
    private javax.swing.JLabel jLabelFondoVerde;
    private javax.swing.JLabel jLabelFondoVerde1;
    private javax.swing.JLabel jLabelFondoVerde2;
    private javax.swing.JLabel jLabelFondoVerde4;
    private javax.swing.JLabel jLabelLargoFalda;
    private javax.swing.JLabel jLabelLargoManga;
    private javax.swing.JLabel jLabelTalle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtAccesorios;
    private javax.swing.JTextField txtBocaM;
    private javax.swing.JTextField txtBusto;
    private javax.swing.JTextField txtCadera;
    private javax.swing.JTextField txtCintura;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtEspalda;
    private javax.swing.JTextField txtFechaE;
    private javax.swing.JTextField txtFechaI;
    private javax.swing.JTextField txtLargoF;
    private javax.swing.JTextField txtLargoM;
    private javax.swing.JTextField txtTallado1;
    private javax.swing.JTextField txtTallado2;
    private javax.swing.JTextField txtTalle;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
