/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import javax.swing.JOptionPane;

/**
 *
 * @author jsant
 */
public class Pedidos extends javax.swing.JFrame {

    /**
     * Creates new form Pedidos
     */
    public Pedidos() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabelBusto = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabelCintura = new javax.swing.JLabel();
        jLabelTalle = new javax.swing.JLabel();
        jLabelLargoFalda = new javax.swing.JLabel();
        jLabelEspalda = new javax.swing.JLabel();
        jLabelCadera = new javax.swing.JLabel();
        jLabelBocaManga = new javax.swing.JLabel();
        jLabelLargoManga = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButtonIniciar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldFecha1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldFecha2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldTallado1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldTallado2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextFieldCliente = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextFieldTotal = new javax.swing.JTextField();
        jButtonHistorial = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaAccesorio = new javax.swing.JTextArea();
        jLabelFondoVerde = new javax.swing.JLabel();
        jLabelFondoVerde2 = new javax.swing.JLabel();
        jLabelFondoVerde1 = new javax.swing.JLabel();
        jLabelFondoVerde4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setText("Registro Pedido");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 370, -1));

        jLabelBusto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelBusto.setText("Busto: ");
        getContentPane().add(jLabelBusto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 570, 90));

        jLabelCintura.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelCintura.setText("Cintura: ");
        getContentPane().add(jLabelCintura, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        jLabelTalle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelTalle.setText("Talle: ");
        getContentPane().add(jLabelTalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));

        jLabelLargoFalda.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelLargoFalda.setText("Largo Falda: ");
        getContentPane().add(jLabelLargoFalda, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, -1));

        jLabelEspalda.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelEspalda.setText("Espalda: ");
        getContentPane().add(jLabelEspalda, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, -1, -1));

        jLabelCadera.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelCadera.setText("Cadera: ");
        getContentPane().add(jLabelCadera, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, -1, -1));

        jLabelBocaManga.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelBocaManga.setText("Boca Manga: ");
        getContentPane().add(jLabelBocaManga, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, -1, -1));

        jLabelLargoManga.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelLargoManga.setText("Largo Manga: ");
        getContentPane().add(jLabelLargoManga, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Descripción: ");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 290, 140, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, 140, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, 140, -1));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 240, 140, -1));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 140, -1));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 140, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 140, -1));

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 140, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Confirmar");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 330, -1, -1));

        jButtonIniciar.setBackground(new java.awt.Color(0, 0, 255));
        jButtonIniciar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonIniciar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonIniciar.setText("Guardar");
        jButtonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 750, -1, -1));

        jButtonCancelar.setBackground(new java.awt.Color(255, 0, 0));
        jButtonCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 750, 90, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Fecha Inicial");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, -1, -1));

        jTextFieldFecha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFecha1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldFecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, 140, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("Fecha Entrega");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 560, -1, -1));

        jTextFieldFecha2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFecha2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldFecha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 560, 140, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("Tallado 1");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 610, -1, -1));
        getContentPane().add(jTextFieldTallado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 610, 140, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setText("Tallado 2");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 660, -1, -1));
        getContentPane().add(jTextFieldTallado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 660, 140, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setText("Accesorios");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 510, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setText("Cliente");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 610, -1, -1));
        getContentPane().add(jTextFieldCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 610, 140, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setText("Total");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 660, -1, -1));
        getContentPane().add(jTextFieldTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 660, 140, -1));

        jButtonHistorial.setBackground(new java.awt.Color(0, 0, 0));
        jButtonHistorial.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonHistorial.setForeground(new java.awt.Color(255, 255, 255));
        jButtonHistorial.setText("Historial");
        jButtonHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHistorialActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 750, 90, -1));

        jTextAreaAccesorio.setColumns(20);
        jTextAreaAccesorio.setRows(5);
        jScrollPane1.setViewportView(jTextAreaAccesorio);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 500, -1, -1));

        jLabelFondoVerde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoVerde.jpg"))); // NOI18N
        getContentPane().add(jLabelFondoVerde, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 410, 320, 410));

        jLabelFondoVerde2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoVerde.jpg"))); // NOI18N
        jLabelFondoVerde2.setText("jLabel1");
        getContentPane().add(jLabelFondoVerde2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 320, -1));

        jLabelFondoVerde1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoVerde.jpg"))); // NOI18N
        getContentPane().add(jLabelFondoVerde1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 410));

        jLabelFondoVerde4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoVerde.jpg"))); // NOI18N
        getContentPane().add(jLabelFondoVerde4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 610, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jButtonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarActionPerformed
        JOptionPane.showMessageDialog(null, "Los datos se guardaron correctamente");
    }//GEN-LAST:event_jButtonIniciarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        Menu newframe = new Menu();
        newframe.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTextFieldFecha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFecha1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFecha1ActionPerformed

    private void jTextFieldFecha2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFecha2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFecha2ActionPerformed

    private void jButtonHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHistorialActionPerformed
        PedidosVer newframe = new PedidosVer();
        newframe.setVisible(true);
    }//GEN-LAST:event_jButtonHistorialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonHistorial;
    private javax.swing.JButton jButtonIniciar;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabelBocaManga;
    private javax.swing.JLabel jLabelBusto;
    private javax.swing.JLabel jLabelCadera;
    private javax.swing.JLabel jLabelCintura;
    private javax.swing.JLabel jLabelEspalda;
    private javax.swing.JLabel jLabelFondoVerde;
    private javax.swing.JLabel jLabelFondoVerde1;
    private javax.swing.JLabel jLabelFondoVerde2;
    private javax.swing.JLabel jLabelFondoVerde4;
    private javax.swing.JLabel jLabelLargoFalda;
    private javax.swing.JLabel jLabelLargoManga;
    private javax.swing.JLabel jLabelTalle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextAreaAccesorio;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextFieldCliente;
    private javax.swing.JTextField jTextFieldFecha1;
    private javax.swing.JTextField jTextFieldFecha2;
    private javax.swing.JTextField jTextFieldTallado1;
    private javax.swing.JTextField jTextFieldTallado2;
    private javax.swing.JTextField jTextFieldTotal;
    // End of variables declaration//GEN-END:variables
}
